In [1]:
my_dict ={}

In [2]:
type(my_dict)

dict

In [3]:
my_dict_1 = {"Name":['Aman','Anoop','Priyanka'],"age":[12,13,15]}

In [4]:
my_dict_1["age"]

[12, 13, 15]

In [5]:
len(my_dict_1)

2

In [6]:
my_dict_1.items()

dict_items([('Name', ['Aman', 'Anoop', 'Priyanka']), ('age', [12, 13, 15])])

In [7]:
print(dir(my_dict_1)) #keys much be unique 

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [8]:
my_dict_1.clear()
my_dict_1

{}

In [12]:
my_dict_2 = {"Name":['Aman','Anoop','Priyanka'],"age":[12,13,15]}

In [13]:
my_dict_2

{'Name': ['Aman', 'Anoop', 'Priyanka'], 'age': [12, 13, 15]}

In [14]:
set_a = {1,1,2,3,4,5,6,7}

In [15]:
set_a

{1, 2, 3, 4, 5, 6, 7}

In [16]:
print(dir(set_a))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [17]:
list_a = [11,4,6,8,9,90,30]
list_b = [11,34,90,98,88,89]


In [25]:
list(set(list_a).intersection(set(list_b)))

[90, 11]

In [21]:
list(set(list_a).difference(set(list_b)))

[4, 6, 8, 9, 30]

In [22]:
my_dict_2.items()

dict_items([('Name', ['Aman', 'Anoop', 'Priyanka']), ('age', [12, 13, 15])])

In [24]:
for key , value in my_dict_2.items():
    print("key is {} and value is {}".format(key,value))

key is Name and value is ['Aman', 'Anoop', 'Priyanka']
key is age and value is [12, 13, 15]


In [30]:
def calnum(a,b,c):
    sum_num = a+b+c
    diff_num = a-b
    print(sum_num,diff_num)

In [31]:
calnum(12,23,34)

69 -11


python function

1. def keyword
2. Function name 
2. Function statements
4. parameters
5. Return statements

 lambda or anonymous function
 no def
 lambda //single line finction 

In [26]:
result = lambda a,b,c:a+b+c

In [27]:
result(12,23,34)

69

In [32]:
sq = lambda x:x**2

In [33]:
sq(25)

625

package vs module vs lib 

numpy
pandas
matplotlib
seaborn


In [35]:
import numpy as np

1D array

In [57]:
a_list = [11,12,13,14,15]

In [37]:
d_1 = np.array(a_list)
d_1

array([11, 12, 13, 14, 15])

In [38]:
d_1[:2]

array([11, 12])

In [39]:
print(dir(d_1))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [40]:
d_1.ndim

1

2D array

In [86]:
d_2 =np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22],[23,24,25,26]])

In [42]:
d_2

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [44]:
d_2.ndim

2

In [45]:
d_2.shape

(4, 4)

In [46]:
d_2.size

16

In [47]:
d_2[0,1]

12

In [48]:
d_2[0][1]

12

In [49]:
d_2.sum()

296

In [50]:
d_2.sum(axis = 0) #column wise summation

array([68, 72, 76, 80])

In [55]:
d_2.sum(axis = 1) #row wise summation 

array([50, 66, 82, 98])

In [56]:
d_2.sum(axis = 1)[2]

82

In [58]:
d_2[:,0]

array([11, 15, 19, 23])

In [59]:
d_2[0,:]

array([11, 12, 13, 14])

In [87]:
d_2[2:,2:]

array([[21, 22],
       [25, 26]])

In [88]:
d_2[0:2,0:2]

array([[11, 12],
       [15, 16]])

In [89]:
d_2[0:4:3,0:4:3]

array([[11, 14],
       [23, 26]])

In [80]:
d_3 = np.array([[11,12,13],[14,15,16],[17,18,19]])

In [81]:
d_3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [82]:
d_3[1:,1:]

array([[15, 16],
       [18, 19]])

In [83]:
d_3[0:3:2,0:3:2]

array([[11, 13],
       [17, 19]])

In [84]:
d_3[::2,::2]

array([[11, 13],
       [17, 19]])

In [85]:
d_3[::-1,::-1]

array([[19, 18, 17],
       [16, 15, 14],
       [13, 12, 11]])

In [90]:
d_3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [92]:
d_3.max()

19

In [93]:
d_3.argmax()

8

In [94]:
d_3.argmin()

0

In [95]:
d_3.mean()

15.0

series

In [98]:
import pandas as pd

In [102]:
my_list = [11,12,13,14]

In [104]:
my_series = pd.Series(my_list)

In [105]:
print(dir(my_series))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror_

In [107]:
my_series

0    11
1    12
2    13
3    14
dtype: int64

In [110]:
my_series[0:2]

0    11
1    12
dtype: int64

Data Frame

In [113]:
my_class_details = {"Name":["Aman","Ankur","Smriti"],"Age":[11,12,13],"score":[80,90,89]}

In [114]:
my_class_details

{'Name': ['Aman', 'Ankur', 'Smriti'],
 'Age': [11, 12, 13],
 'score': [80, 90, 89]}

In [117]:
df = pd.DataFrame(my_class_details)

In [118]:
df

Name  Age  score
0    Aman   11     80
1   Ankur   12     90
2  Smriti   13     89

In [119]:
df["Name"]

0      Aman
1     Ankur
2    Smriti
Name: Name, dtype: object

In [120]:
df["Age"]

0    11
1    12
2    13
Name: Age, dtype: int64

In [121]:
print(dir(df))

['Age', 'Name', 'T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__',